version: "3.8"
services:
    postgres:
        build: ./db
        networks:
            - backend
        ports:
            - ${POSTGRES_POXY_PORT}:${POSTGRES_PORT}
        volumes:
            - ${POSTGRES_PATH_DATA}:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: always
        image: petrachkov/postgres
        container_name: ${DB_CONTAINER}
    node:
        build: .
        networks:
            - backend
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - ./src:/app/src
            - ./logs:/app/logs
        depends_on:
            - postgres
        environment:
            PORT: ${PORT}
            NODE_ENV: ${NODE_ENV}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            AUTH_MODE: ${AUTH_MODE}
            DATE_FORMAT: ${DATE_FORMAT}
            POSTGRES_HOST: ${DB_CONTAINER}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: unless-stopped
        image: petrachkov/node
        container_name: ${NODE_CONTAINER}
networks:
    backend:
        driver: bridge
        name: bridge-backend
